steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
  '--build-arg', 'PROJECT_ID=$PROJECT_ID',
  '-t', 'northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/slackbotopenai/botimage:latest', '.' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'beta', 'compute', 'instance-groups', 'managed', 'rolling-action', 'start-update', 'instance-group-slackgpt3bot-1', '--project=$PROJECT_ID', '--version=template=https://www.googleapis.com/compute/beta/projects/$PROJECT_ID/global/instanceTemplates/instance-template-slackgpt3bot-1', '--zone=northamerica-northeast1-a',
  '--type=proactive', '--max-surge=0', '--max-unavailable=1', '--min-ready=0', '--minimal-action=restart', '--replacement-method='substitute' ]
images:
- 'northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/slackbotopenai/botimage:latest'
