steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
  '--build-arg', 'PROJECT_ID=$PROJECT_ID',
  '-t', 'northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/slackbotopenai/botimage:latest', '.' ]
images:
- 'northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/slackbotopenai/botimage:latest'
