steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
  '--build-arg', 'PROJECT_ID=$PROJECT_ID',
  '-t', 'northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/slackbotopenai/botimage:latest', '.' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'gcloud', 'beta', 'compute', 'instance-groups', 'managed', 'rolling-action', 'start-update', 'instance-group-slackgpt3bot-1', '--project=$PROJECT_ID' ]
images:
- 'northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/slackbotopenai/botimage:latest'
