steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
  '--build-arg', 'SLACK_BOT_GPT3_TOKEN=$_SLACK_BOT_GPT3_TOKEN',
  '--build-arg', 'SLACK_APP_GPT3_TOKEN=$_SLACK_APP_GPT3_TOKEN',
  '--build-arg', 'OPENAI_API_KEY=$_OPENAI_API_KEY',
  '-t', 'northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/slackbotopenai/botimage:tag10', '.' ]
images:
- 'northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/slackbotopenai/botimage:tag10'
substitutions: 
  _SLACK_BOT_GPT3_TOKEN: ''
  _SLACK_APP_GPT3_TOKEN: ''
  _OPENAI_API_KEY: ''
- name: gcr.io/cloud-builders/gcloud
  args: [ compute, instance-groups, managed, rolling-action, start-update, instance-group-slackbot-1, --project=home-37592, --zone=us-central1-a ]


